# The URL the site will be built for
base_url = "/"
title = "Software must die."
description = "Personal website of Achraf B."

# Configure the local theme.

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
bottom_footnotes = true
smart_punctuation = true

[markdown.highlighting]
light_theme = "gruvbox-light-soft"
dark_theme = "gruvbox-dark-soft"

[extra]
# Put all your custom variables here
author = "@clflushopt"
auto_date = true
